name: Label PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: nodejs/node-pr-labeler@v1
        with:
          configuration-path: .github/label-pr-config.yml
